Added service controllers
Manish-d-hub/uber-clone-api pull request #2
Opened 2022-04-11 11:53 UTC by Manish-d-hub

*This PR*

- Added service controllers for api
- Code Refactoring
- Testing

2022-04-11 13:27 UTC, Dj911 reviewed
@Manish-d-hub Please check the comments and do the needfull

2022-04-11 13:27 UTC, Dj911 commented on src/components/booking/bookingService.js
> +  catchAsync(async (req, res) => {
req,res parameter should always be in controller file, not inside service file

2022-04-11 13:27 UTC, Dj911 commented on src/components/ride/rideService.js
> +    const rides = await Model.find({
Use appropriate naming convention for variables. Like for user model it would be User.find({})

2022-04-11 13:27 UTC, Dj911 commented on src/components/booking/bookingService.js
> +    const bookings = await Model.find({ user: req.user.id });
Use destructuring for req.user.id

2022-04-11 13:27 UTC, Dj911 commented on src/components/booking/bookingService.js
> +export const bookOne = (Model_1, Model_2) =>
Instead of passing Model as parameter, import that model inside the service file

2022-04-13 05:08 UTC, Dj911 requested changes
Please apply the requested change

2022-04-13 05:08 UTC, Dj911 commented on src/components/ride/rideRoutes.js
> +router.post('/create-ride', rideController.createRide);
Use obj destructuring in Import as well

2022-04-13 05:24 UTC, Manish-d-hub commented on src/components/ride/rideRoutes.js
> +router.post('/create-ride', rideController.createRide);
Changes done

2022-04-13 09:53 UTC, Dj911 requested changes
Make the requested change @Manish-d-hub

2022-04-13 09:53 UTC, Dj911 commented on src/components/ride/rideRoutes.js
> +router.post('/create-ride', rideController.createRide);
use "import {createRide} fro './controller.js'" instead of import all the functions from the controller file

2022-04-13 09:53 UTC, Dj911 commented on src/components/user/userRoutes.js
> +router.route('/update-me').patch(protect, updateUser);
If a route has same http methods like GET,POST then instead of using "router.route('/url').post(funcA)" use "router.post('/url',funcA)"

2022-04-14 09:42 UTC, merged